scope: books
name: patroni-1

restapi:
  listen: 0.0.0.0:8008
  connect_address: patroni-1:8008

etcd:
  hosts: etcd:2379

postgresql:
  listen: 0.0.0.0:5432
  connect_address: patroni-1:5432
  data_dir: /home/postgres/pgdata/pgroot/data
  parameters:
    shared_preload_libraries: "pg_stat_statements"

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    postgresql:
      parameters:
        wal_level: replica
        max_wal_senders: 10
        max_replication_slots: 10
  initdb:
    - encoding: UTF8
    - data-checksums